#!/bin/bash

set -x

DIR=$(dirname $(dirname $(realpath $0)))
source $DIR/ENV

GOT_VERSION=0
for arg in $@; do
	if [[ $arg == "-V" ]] || [[ $arg == --version* ]]; then
		GOT_VERSION=1
	fi
done

VERSION_PARAM=""
if [ "$GOT_VERSION" == "0" ] && [ -f $VERSION_FILE ]; then
       V=$(cat $VERSION_FILE)
       echo "Using last autodeploy version: $V"
	VERSION_PARAM="--version=$V"
fi

$BASE/aprox-docker/init-aprox-server-no-vols.py  -E ${ETC_URL} \
                                                 --port=$PORT \
                                                 --sshdir=$SSH \
                                                 --name=$CONTAINER_NAME \
                                                 --image=$IMAGE_NAME \
                                                 --logs=$BASE/logs \
                                                 --data=$BASE/data \
                                                 --config=$BASE/etc \
                                                 --storage=$BASE/storage \
                                                 $VERSION_PARAM \
                                                 $EXTRA_PARAMS $@
