#!/bin/bash

set -x

DIR=$(dirname $(dirname $(realpath $0)))
source $DIR/ENV

systemctl stop $SERVICE_NAME
docker stop $CONTAINER_NAME
docker rm $CONTAINER_NAME

docker pull $IMAGE_NAME

$BASE/scripts/init-aprox -q $@

systemctl start $SERVICE_NAME
journalctl -f
